(cl:defpackage ssl_msgs-msg
  (:use )
  (:export
   "<DYNAMICOBSTACLE>"
   "DYNAMICOBSTACLE"
   "<LINEARMOTIONINSTANT>"
   "LINEARMOTIONINSTANT"
   "<MOTIONCONSTRAINTS>"
   "MOTIONCONSTRAINTS"
   "<ROBOTINSTANT>"
   "ROBOTINSTANT"
   "<STATICOBSTACLE>"
   "STATICOBSTACLE"
   "<PATH_PLAN>"
   "PATH_PLAN"
   "<POINT_2D>"
   "POINT_2D"
   "<TRAJECTORY>"
   "TRAJECTORY"
  ))

